# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
      
name: Publish PyPI
on: 
  release:
    types: [published]
jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -q -y --no-install-recommends libglu1-mesa-dev libopenslide-dev 
        python -m pip install --upgrade pip
        pip install build==0.10.0 wget numpy SimpleITK twine
    - name: Build package
      env:
        # PYM2AIA_VERSION_TAG: ${{ github.event.release.tag_name }}
        PYM2AIA_VERSION_TAG: 0.5.12
      run: |
        python setup_prepare.py --linux --download -v v2023.10.6
        python -m build
        mv dist/m2aia-${PYM2AIA_VERSION_TAG}-py3-none-any.whl dist/m2aia-${PYM2AIA_VERSION_TAG}-py3-none-manylinux_2_31_x86_64.whl
        python setup_prepare.py --windows --download -v v2023.10.8
        python -m build
        mv dist/m2aia-${PYM2AIA_VERSION_TAG}-py3-none-any.whl dist/m2aia-${PYM2AIA_VERSION_TAG}-py3-none-win_amd64.whl
        python setup_prepare.py --windows --linux -v v2023.10.6
        python -m build
        rm dist/m2aia-${PYM2AIA_VERSION_TAG}-py3-none-any.whl
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: >-
      Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/m2aia  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: >-
      Sign the Python distribution with Sigstore
      and upload them to GitHub Release
    needs:
    - publish-to-pypi
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v1.2.3
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        '${{ github.ref_name }}' dist/**
        --repo '${{ github.repository }}'
